version: "3.4"
services:

  dev:
    build:
      target: dev
    ports:
      - 8000:8000
    volumes:
      - ./metrics:/app/metrics
      - ./tests:/app/tests
      - ./main.py:/app/main.py
    command: /start-reload.sh


  test:
    build:
      target: dev
    volumes:
      - ./metrics:/app/metrics
      - ./tests:/app/tests
    command: pytest -s


  prod:
    restart: unless-stopped
    build:
      target: prod
    ports:
      - 8000:8000
    ## To deploy in production with https://github.com/nginx-proxy/nginx-proxy
    environment:
      - VIRTUAL_HOST={{cookiecutter.host_url.replace('http://', '').replace('https://', '')}}
      - LETSENCRYPT_HOST={{cookiecutter.host_url.replace('http://', '').replace('https://', '')}}
      - VIRTUAL_PORT=8000

    ## If need to pass secrets to the API:
    # env_file:
    #   - secrets.env
